### ISSUE TITLE
إستخدام ملف الترويسة math.h بدلًا من cmath يسبب أخطاء في المشروع

### ISSUE THREAD

**Issue by iTzVoko** [alifcommunity/Alif5#25]
## القضية
السلام عليكم ورحمة الله وبركاته

يجب إستخدام ملف الترويسة `cmath` بدلًا من `math.h`؛ لأنه يؤدي الى فشل ترجمة المشروع في بعض المترجمات المعروفة، وتجنب صراعات/تعارضات الأسماء مُمكنة الحدوث بسبب ملف الترويسة `math.h`.

## لماذا؟
لا تقتصر الأسباب فقط على أن القضية المذكورة أعلاه ستُصلح مشكلة عدم قدرة المُترجم على ترجمة المشروع، وإنّما توجد بعض النقاط التي يجب ذكرها، فعلى سبيل المثال:

 • مساحة الأسم (namespace): ثوابت ودوال ملف الترويسة `cmath` مُعرّفة داخل مساحة الأسم `std`، وهذا بخلاف ثوابت ودوال ملف الترويسة `math.h`؛ الذي يضهر دواله وثوابته في العلن.
ليساعد `cmath` على تجنّب صراعات وتعارُضات أسماء المتغيرات والدوال المُعرّفة من قبل المُستخدم (المطور).

 •  الدوال المُثقّلة (overloaded functions): يوفر `cmath` دوال مُثقّلة للعديد من دواله الرياضية؛ مما يسمح لك بإستخدامها مع أنواع وسيطات مختلفة (مثل `float` أو `double` أو long double`)`. بينما يوفر `math.h` وظائف ذات نوع وسيطة واحد فقط.

• توافقيته مع مميزات لغة ++C: صُمّم `cmath` ليكون متوافقًا مع ميزات ++C مثل القوالب والدوال المُثقّلة ومساحات الأسماء. وفي المقابل، لا يحتوي `math.h` على هذا التوافق، لذلك قد يكون من الصعب استخدامه في هذا المشروع وغيره من مشاريع لغة ++C التي يمكنها الإستفادة من هذه الميزات.

• وأخيرًا وليس آخرًا، قابليته على التنقّل: ملف الترويسة `cmath` هو جزء من مكتبة ++C القياسية/المعيارية، ممّا يعني ضمان كونه متاحًا في جميع المُترجمات وأنظمة التشغيل وعمله بكفاءة.

## خطوات إعادة إنتاج المشكلة
سواءًا إستخدمت مترجم `++g` أم `++clang` فكلاهما يمتنعان عن ترجمة المشروع، فإن كتبت السطر الآتي على سبيل المثال:
```bash
g++ -std=c++17 -o alif5 source/Alif5.cpp
```
سيخبرك بوجود خطأ، كما في الصورة التالية :
![20230224_170927](https://user-images.githubusercontent.com/70109144/221200516-9e6efb3e-1f2f-420d-a796-396eea6c208a.png)

أردت توضيح هذه القضية بسبب رؤيتي أيضًا لبعض المبرمجين والمُعلّمين على الإنترنت يستخدمون ملف الترويسة `math.h` في شروحاتهم، مشاريعهم، وتطبيقاتهم المختلفة بدلًا من `cmath` الي يعتبر ملف ترويسة معياري في لغة ++C.

**Comment by iTzVoko** [comment]
سأعمل على إصلاح المشكلة بإستبدال ملف الترويسة `math.h`:
```diff
-#include <math.h>
+#include <cmath>
```

في ملف الشفرة المصدرية `Alif5.cpp`.

**Comment by Shad7ows** [comment]
تمت مراجعة المشكلة
يمكنك رفع pull request يحتوي على إصلاح الخلل وسيتم مراجعته والموافقة عليه بإذن الله
